name: MusicBot Docker Build

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
  schedule:
    - cron: "0 0 * * 6"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Extract JMB_VERSION from Dockerfile
        id: extract_version
        shell: bash
        run: |
          JMB_VERSION=$(grep -E '^ENV JMB_VERSION' Docker/Dockerfile | awk '{print $3}')
          echo "JMB_VERSION=$JMB_VERSION" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./Docker
          push: true
          provenance: mode=max
          sbom: true
          tags: |
            clifford64/musicbot:latest
            clifford64/musicbot:${{ env.JMB_VERSION }}
